name: CI/CD Pipeline
on:
  push:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: pip install -r app/requirements.txt
    - name: Test Flask app
      run: python -m unittest discover
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Build and push Docker image
      run: |
        docker build -t thorlongus/telco-churn:latest .
        docker push thorlongus/telco-churn:latest
    - name: Login to Heroku Container Registry
      run: echo "${{ secrets.HEROKU_API_KEY }}" | docker login --username=_ --password-stdin registry.heroku.com
    - name: Build and push to Heroku
      run: |
        docker build -t registry.heroku.com/telco-churn-app-2025/web .
        docker push registry.heroku.com/telco-churn-app-2025/web
    - name: Release to Heroku
      run: heroku container:release web --app telco-churn-app-2025
      env:
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}